### ISSUE TITLE
mysql blocks csv imports on latest versions

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/Installation-Guides#75]
https://stackoverflow.com/questions/52030767/how-to-solve-error-1148-from-mysql-workbench-and-not-cmd

https://bugs.mysql.com/bug.php?id=91872

Suggest we just link to version 5.7. What do you think @dave-mills?

**Comment by chrismclarke** [comment]
actually I had  8.0.13... will try latest 8.0.14

**Comment by chrismclarke** [comment]
Still not fixed, better thread of discussion here (lots of angry folk):
https://bugs.mysql.com/bug.php?id=91891

**Comment by chrismclarke** [comment]
I spoke to shiphar and during the workshop we gave the 5.7 installers to everybody so I think we should change the mysql install guide to prompt users to install that version (until we can be assured the latest version works as desired)

**Comment by dave-mills** [comment]
I'm pretty sure this is solved if you make sure to tick the "legacy authentication" box when installing? (I remember there was a good reason I included that in the MySQL installation doc, but I can't remember exactly what that was! 

I'll test it here quickly to see. Otherwise, we can go back to suggesting 5.7 as a nice, stable one.

**Comment by dave-mills** [comment]
Ok, ignore my previous comment - the legacy authentication thing is because clients like Heidi don't support the new sha-whatever authentication system yet.

The issue with the LOCAL INFILE command can be resolved in Heidi by selecting "Client parsed file contents" under Method. 

I had a vague memory of giving advice on which method to use. Looking in our OneNote I've found a note mentioning "Client parses data" when importing a csv, so I think telling people to do that is in-line with what we recommended at the workshop (I think after some issue with the other method...)

**Suggestion**: I think ensuring that "client parses data" is set is fine, rather than suggesting people stick to an older version. I just checked the DB Forge importer too and that appears to avoid the LOCAL INFILE issue by default. 

![Screenshot 2019-01-24 13.43.37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bc896767cdc81a00f074cb/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416763e7b50e37a23cbb77bf1112c43434d0eee1e020a17b8eb8339a3e46976db5f03bbd26a5675c66e11acbed14ebc04b923825d99a4fedb1294b7607caddecd5d340c041f83fe5831a89a48cf5cf44ce44f5cb65e.png)

**Comment by chrismclarke** [comment]
I tried that box and it still failed, have you tested it working correctly?

**Comment by dave-mills** [comment]
Hm. Yeah, it works fine for my little 2-column test. What data are you importing? Can I try with your db setup?

**Comment by chrismclarke** [comment]
The old setup is now dead as I reinstalled 5.7. I think let’s just hope things work given current advice and if not have a means people can contact us to raise issues.

**Comment by dave-mills** [comment]
Sure thing. I'll close this thread for now. If you happen to have seen the errors in the Heidi console that you were getting, we can re-open and I can try and recreate the issue here as I have a fresh new 8.14 install on Windows.
